### ISSUE TITLE
Utility function for properly quoting table names, full-qualified or not

### ISSUE THREAD

**Issue by amotl** [crate/sqlalchemy-cratedb#69]
## About
@seut improved the table name quoting function in CrateDB Toolkit.

- https://github.com/crate-workbench/cratedb-toolkit/pull/172

My thoughts are whether this could also be useful for users of the CrateDB SQLAlchemy dialect in one way or another, mostly on utility use cases like introspecting / reflecting table information using SQLAlchemy's inspector.

It does not need to happen today or tomorrow, because Toolkit is exactly also for incubating purposes, but it may happen to migrate this method on behalf of a future iteration. wdyt?

**Comment by seut** [comment]
> My thoughts are whether this could also be useful for users of the CrateDB SQLAlchemy dialect in one way or another, mostly on utility use cases like introspecting / reflecting table information using SQLAlchemy's inspector.

I don't think that this utility function can go into the SQLAlchemy dialect as this helper will also work with full-qualified names while this is not expected to do this inside SQLAlchemy. The `quote` method a dialect can override is only intended to be used with non-full-qualified identifiers, but not with fqn ones which e.g. contain a schema.

**Comment by amotl** [comment]
All right. Maybe it was a Schnapsidee. Let's close this issue again, thanks for your response.
